### ISSUE TITLE
Braintree dep > 3.30 breaks the example

### ISSUE THREAD

**Issue by stephgosling** [braintree/braintree_flask_example#11]
### General information

* Environment: Sandbox (but presumably prod too)
* Language, language version, and OS: Python 2.7.x and Python 3.5.x both on Ubuntu 16.04 and in the provide docker-compose environment.
### Issue description
In a nutshell:

The requirements.txt specifies a braintree dependency of >= 3.22 however the latest (3.36) will fail with the following error:

```
(venv3) dino braintree_flask_example $ python3.5 app.py 
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    import braintree
  File "/home/steph/git/braintree_flask_example/venv3/lib/python3.5/site-packages/braintree/__init__.py", line 1, in <module>
    from braintree.ach_mandate import AchMandate
  File "/home/steph/git/braintree_flask_example/venv3/lib/python3.5/site-packages/braintree/ach_mandate.py", line 2, in <module>
    from braintree.util.datetime_parser import parse_datetime
ImportError: No module named 'braintree.util.datetime_parser'
```

This is reproduceable both in virtualenvs of Python 2 and Python 3 on Ubuntu 16.04 and also in the provided docker-compose yaml. I was able to get the example to run with the following change, but I haven't looked to see exactly which version of braintree breaks this:

```
diff --git a/requirements.txt b/requirements.txt
index 9c3fb46..034b247 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 Flask>=0.10.1
-braintree>=3.22.0
+braintree==3.30.0
 MarkupSafe>=0.23
 mock>=1.3.0
 Werkzeug>=0.7
```

**Comment by sdcoffey** [comment]
Hey @stephgosling,

This was indeed an issue in 3.36.0, and it's been fixed as of [3.37.0](https://github.com/braintree/braintree_python/blob/master/CHANGELOG.md#3370). I'm going to close this issue, please open another issue if you're still experiencing problems.
