### ISSUE TITLE
ERROR: No value passed to payment issue

### ISSUE THREAD

**Issue by pradipyadavpk** [braintree/braintree_flask_example#17]
### General information

* Environment:  Sandbox 
* Language, language version, and OS: Python 2.7 on Linux Mint Mate 18 

### Issue description

I cloned this project https://github.com/braintree/braintree_flask_example and applied braintree sandbox credentials in example.env file and after run the project i am getting below stack trace in chrome browser console :
{stack: "Error: No value passed to payment↵ at https://w…aypalobjects.com/api/checkout.4.0.166.js:2856:13)", errtype: "[object Error]", timestamp: 1512406360681, windowID: "99a6bf0489", pageID: "d6d9926518", …}country: "GB"env: "sandbox"errtype: "[object Error]"host: "www.sandbox.paypal.com"lang: "en"pageID: "d6d9926518"path: "/webapps/hermes/button"prev_corr_ids: ""referer: "http://localhost:4567"stack: "Error: No value passed to payment↵ at https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:187628↵ at https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:168195↵ at e.dispatch (https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:168649)↵ at e.resolve (https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:167373)↵ at https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:167026↵ at ↵ at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.4.0.166.js:2936:122)↵ at receiveMessage (https://www.paypalobjects.com/api/checkout.4.0.166.js:2835:77)↵ at messageListener (https://www.paypalobjects.com/api/checkout.4.0.166.js:2856:13)"timestamp: 1512406360681uid: "fc21281b3e_ge3dunjshizdo"ver: "4.0.166"windowID: "99a6bf0489"proto: Object ....

i stuck here last 5 days. Please help.

**Comment by crookedneighbor** [comment]
Sounds to me like there is something wrong with your PayPal account Sandbox account. Please [contact our support team](https://developers.braintreepayments.com/forms/contact) so they can figure out what the issue with your account is.
