### ISSUE TITLE
How to limit/control user entry of transaction amounts

### ISSUE THREAD

**Issue by mrcartier** [braintree/braintree_flask_example#24]
### General information

* Environment: Sandbox
* py3 on Ubuntu 16.04 LTS

### Issue description

I'd like to have users enter only 1 of 3 amounts. For example 5.00, 10.00 or 20.00 & I though't I'd just use an if/else to do so inside the new checkout function (def new_checkout) of app.py (see line 31 of app.py). I was thinking if the amount entered is 5,10 or 20 proceed with the transaction, else display some error (ie Error: 81502: Amount is required.). Is there a way to get the transaction amount & check it before moving forward with the transaction OR should I be approaching this a different way? Thanks

**Comment by crookedneighbor** [comment]
I'd have the selection on the front end not pass an amount to your server at all, but instead a value that corresponds to a specific amount that can be looked up on the backend. IE, if you pass `choice-a` that could correspond to `5.00` and `choice-b` could correspond to `10.00`.

For specific help with your integration, please reach out to our support team. https://help.braintreepayments.com/
