### ISSUE TITLE
Production .env config

### ISSUE THREAD

**Issue by mrcartier** [braintree/braintree_flask_example#26]
### General information

* Environment: (moving toward) Production
* Language, language version, and OS: py3 Ubuntu 16.04

### Issue description
More of question than integration issue. Working fine with the example.env below

BT_ENVIRONMENT='sandbox'
BT_MERCHANT_ID='your braintree merchant id'
BT_PUBLIC_KEY='your braintree public key'
BT_PRIVATE_KEY='your braintree private key'
APP_SECRET_KEY='your unique secret key; a long, random set of characters'

now looking to move to production credentials & was going to update only top 4 lines of .env like so

BT_ENVIRONMENT='production'
BT_MERCHANT_ID='your PRODUCTION braintree merchant id'
BT_PUBLIC_KEY='your PRODUCTION braintree public key'
BT_PRIVATE_KEY='your PRODUCTION braintree private key'
APP_SECRET_KEY='your unique secret key; a long, random set of characters'

but before I move forward & try a few low-value test transactions just wanted to check if there's any additional updates/changes/recommendations needed to the .env file so it'll work properly with production credentials. Thanks

**Comment by crookedneighbor** [comment]
Those are the only changes required in the .env file. I would recommend changing the app to not take the amount for the transaction from the client before actually using it in production :).

For additional help, I'd recommend reaching out to our support team. They're the best ones equipped to help you with the specific needs of your integration. https://help.braintreepayments.com/
