### ISSUE TITLE
README Clarification

### ISSUE THREAD

**Issue by annihilatrix** [braintree/braintree_flask_example#9]
Thanks so much for the great example flask project for integrating braintree in python! 

I just wanted to mention a small opportunity for clarification in the README. It says "Copy the example.env file to .env", which doesn't indicate that .env is a file as well. I literally created my typical virtualenv named env and moved the .env file into it (and to various other places in the project) for several minutes. Something like "Rename the example.env file to .env" or something to indicate that .env is a file which is remaining in the same place might save another n00b from fumbling around in the future. ;)

**Comment by danakatz** [comment]
Hi @annihilatrix, 

Thank you for the suggestion! We've [clarified the setup instructions](https://github.com/braintree/braintree_flask_example/commit/e1c9d82ada2c433d5248de260b225ae86ab3a7cb). Glad you got everything up and running -- feel free to let us know if you run into any other issues or opportunities for improvement.
